baseurl = "https://suspicious-jones-985cfd.netlify.app/"
defaultContentLanguage = "en"
disqusShortname = "devcows"
googleAnalytics = ""
languageCode = "en-us"
paginate = 10
summaryLength = 70
theme = "hugo-universal-theme"
title = "BeningAbadi"
[[menu.main]]
identifier = "menu.home"
name = "Home"
url = "/"
weight = 14
[[menu.main]]
name = "Option 1: Default Page"
parent = "menu.home"
url = "/"
weight = 13
[[menu.main]]
name = "Option 2: Application"
parent = "menu.home"
url = "/"
weight = 25
[[menu.main]]
name = "Option 3: Startup"
parent = "menu.home"
url = "/"
weight = 34
[[menu.main]]
name = "Option 4: Agency"
parent = "menu.home"
url = "/"
weight = 38
[[menu.main]]
identifier = "menu.features"
name = "Features"
url = "/img/template-easy-customize.png"
weight = 33
[[menu.main]]
identifier = "section.shortcodes"
name = "Shortcodes"
parent = "menu.features"
post = 1
weight = 12
[[menu.main]]
name = "Accordions"
parent = "section.shortcodes"
weight = 11
[[menu.main]]
name = "Buttons"
parent = "section.shortcodes"
weight = 32
[[menu.main]]
name = "Content Boxes"
parent = "section.shortcodes"
weight = 37
[[menu.main]]
name = "Horizontal Blocks"
parent = "section.shortcodes"
weight = 41
[[menu.main]]
name = "Default Sticky Header"
parent = "section.headervariations"
weight = 10
[[menu.main]]
name = "No Sticky Header"
parent = "section.headervariations"
weight = 22
[[menu.main]]
name = "Light Header"
parent = "section.headervariations"
weight = 31
[[menu.main]]
identifier = "menu.portfolio"
name = "Portfolio"
url = "/img/template-homepage.png"
weight = 30
[[menu.main]]
identifier = "section.portfolio"
name = "Portfolio"
parent = "menu.portfolio"
post = 1
weight = 9
[[menu.main]]
name = "2 Columns"
parent = "section.portfolio"
weight = 8
[[menu.main]]
name = "2 Columns With Negative Space"
parent = "section.portfolio"
weight = 21
[[menu.main]]
name = "3 Columns"
parent = "section.portfolio"
weight = 29
[[menu.main]]
name = "3 Columns With Negative Space"
parent = "section.portfolio"
weight = 36
[[menu.main]]
name = "4 Columns"
parent = "section.portfolio"
weight = 40
[[menu.main]]
name = "4 Columns With Negative Space"
parent = "section.portfolio"
weight = 44
[[menu.main]]
name = "Portfolio - detail"
parent = "section.portfolio"
weight = 47
[[menu.main]]
identifier = "section.about"
name = "About"
parent = "menu.portfolio"
post = 2
weight = 20
[[menu.main]]
name = "About Us"
parent = "section.about"
weight = 7
[[menu.main]]
name = "Our Team"
parent = "section.about"
weight = 19
[[menu.main]]
identifier = "section.marketing"
name = "Marketing"
parent = "menu.portfolio"
post = 2
weight = 28
[[menu.main]]
name = "Packages"
parent = "section.marketing"
weight = 6
[[menu.main]]
identifier = "menu.allpages"
name = "Semua Pages"
weight = 35
[[menu.main]]
identifier = "section.ap-home"
name = "Home"
parent = "menu.allpages"
post = 1
weight = 5
[[menu.main]]
identifier = "section.ap-about"
name = "About"
parent = "menu.allpages"
post = 1
weight = 18
[[menu.main]]
identifier = "section.ap-marketing"
name = "Marketing"
parent = "menu.allpages"
post = 1
weight = 27
[[menu.main]]
identifier = "section.ap-portfolio"
name = "Portfolio"
parent = "menu.allpages"
post = 2
weight = 4
[[menu.main]]
identifier = "section.ap-userpages"
name = "User Pages"
parent = "menu.allpages"
post = 2
weight = 17
[[menu.main]]
identifier = "section.ap-shop"
name = "Shop"
parent = "menu.allpages"
post = 3
weight = 3
[[menu.main]]
identifier = "section.ap-shoporderprocess"
name = "Shop - Order Process"
parent = "menu.allpages"
post = 3
weight = 16
[[menu.main]]
identifier = "section.ap-contact"
name = "Contact"
parent = "menu.allpages"
post = 4
weight = 2
[[menu.main]]
identifier = "section.ap-pages"
name = "Pages"
parent = "menu.allpages"
post = 4
weight = 15
[[menu.main]]
identifier = "section.ap-blog"
name = "Blog"
parent = "menu.allpages"
post = 4
url = "/blog/"
weight = 26
[[menu.main]]
name = "Blog Listing Big"
parent = "section.ap-blog"
url = "/blog/"
weight = 1
[[menu.main]]
identifier = "menu.blog"
name = "Blog"
url = "/blog/"
weight = 39
[[menu.main]]
name = "Alerts"
parent = "section.shortcodes"
weight = 23
[[menu.main]]
identifier = "section.headervariations"
name = "Header variations"
parent = "menu.features"
post = 2
weight = 24
[[menu.main]]
name = "Option 5: Portfolio"
parent = "menu.home"
url = "/"
weight = 42
[[menu.main]]
identifier = "menu.faq"
name = "FAKU!"
url = "/faq/"
weight = 43
[[menu.main]]
name = "Pagination"
parent = "section.shortcodes"
weight = 45
[[menu.main]]
identifier = "contact"
name = "Contact"
url = "/contact/"
weight = 46
[[menu.main]]
name = "Tabs"
parent = "section.shortcodes"
weight = 48
[[menu.main]]
name = "Portfolio - detail 2"
parent = "section.portfolio"
weight = 49
[[menu.main]]
name = "Typography"
parent = "section.shortcodes"
weight = 50
[[menu.topbar]]
name = "Phone"
pre = "<i class='fas fa-2x fa-phone'></i>"
url = "tel:+12 34 567 89 01"
weight = 1
[[menu.topbar]]
name = "GitHub"
pre = "<i class='fab fa-2x fa-github'></i>"
url = "https://github.com/devcows/hugo-universal-theme"
weight = 2
[[menu.topbar]]
name = "Facebook"
pre = "<i class='fab fa-2x fa-facebook'></i>"
url = "http://facebook.com"
weight = 3
[[menu.topbar]]
name = "Twitter"
pre = "<i class='fab fa-2x fa-twitter'></i>"
url = "http://twitter.com"
weight = 4
[params]
about_us = "<p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.</p>"
address = "<p class=\"text-uppercase\"><strong>Universal Ltd.</strong>\n        <br>13/25 New Avenue\n        <br>Newtown upon River\n        <br>45Y 73J\n        <br>England\n        <br>\n        <strong>Great Britain</strong>\n      </p>\n      "
author = "DevCows"
contact_form_ajax = false
contact_url = "/contact"
copyright = "Bening Abadi di 2022"
date_format = "January 2, 2006"
defaultDescription = "Site template made by devcows using hugo"
defaultKeywords = ["devcows", "hugo", "go"]
default_sharing_image = "img/sharing-default.png"
disabled_logo = false
enableGoogleMaps = false
enableRecaptchaInContactForm = false
facebook_site = ""
formspree_action = "https://formspree.io/sample/of/endpoint"
googleMapsApiKey = "AIzaSyAv7Sza8NSp9_l_g8G2vlo0H4ydEPn_2jY"
googleRecaptchaKey = "site_key_for_google_recaptcha"
latitude = "-12.043333"
logo = "img/logo-kecil.png"
logo_small = "img/logo-kecil.png"
logo_text = "BeningAbadi"
longitude = "-77.028333"
mainSections = ["blog"]
style = "default"
twitter_site = "GoHugoIO"
viewMorePostLink = "/blog/"
[params.carouselCustomers]
auto_play = true
items = 6
pagination_speed = 1000
slide_speed = 2000
[params.carouselHomepage]
auto_play = true
enable = true
pagination_speed = 1000
slide_speed = 1000
[params.carouselTestimonals]
auto_play = true
items = 4
pagination_speed = 1000
slide_speed = 1000
[params.clients]
enable = true
subtitle = ""
title = "Our Clients"
[params.features]
cols = 3
enable = true
[params.footer.recent_posts]
enable = false
[params.recent_posts]
enable = true
hide_summary = false
subtitle = "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo."
title = "From our blog"
[params.see_more]
enable = true
icon = "far fa-file-alt"
link_text = "Check other homepages"
link_url = "#"
subtitle = "We have prepared for you more than 40 different HTML pages, including 5 variations of homepage."
title = "Do you want to see more?"
[params.testimonials]
enable = true
subtitle = "We have worked with many clients and we always like to hear they come out from the cooperation happy and satisfied. Have a look what our clients said about us."
title = "Testimonials"
[params.topbar]
enable = false
text = "<p class=\"hidden-sm hidden-xs\">Contact us on +420 777 555 333 or hello@universal.com.</p>\n      <p class=\"hidden-md hidden-lg\"><a href=\"tel:+420 777 555 333\" data-animate-hover=\"pulse\"><i class=\"fas fa-phone\"></i></a>\n      <a href=\"mailto:hello@universal.com\" data-animate-hover=\"pulse\"><i class=\"fas fa-envelope\"></i></a>\n      </p>\n      "
[params.widgets]
categories = true
search = true
tags = true
[permalinks]
blog = "/blog/:year/:month/:day/:filename/"
[taxonomies]
author = "authors"
category = "categories"
tag = "tags"
