baseurl = "https://suspicious-jones-985cfd.netlify.app/"
defaultContentLanguage = "en"
googleAnalytics = ""
languageCode = "en-us"
paginate = 10
summaryLength = 70
theme = "hugo-universal-theme"
title = "Bening Abadi Jogja"
[[menu.main]]
identifier = "menu.home"
name = "Home"
url = "/"
weight = 14
[[menu.main]]
name = "Option 1: Default Page"
parent = "menu.home"
url = "/"
weight = 13
[[menu.main]]
name = "Option 2: Application"
parent = "menu.home"
url = "/"
weight = 25
[[menu.main]]
identifier = "menu.portfolio"
name = "Portfolio"
url = "/img/template-homepage.png"
weight = 30
[[menu.main]]
identifier = "section.portfolio"
name = "Portfolio"
parent = "menu.portfolio"
post = 1
weight = 9
[[menu.main]]
identifier = "section.about"
name = "About"
parent = "menu.portfolio"
post = 2
weight = 20
[[menu.main]]
name = "Our Team"
parent = "section.about"
weight = 19
[[menu.main]]
identifier = "menu.allpages"
name = "Semua Pages"
weight = 35
[[menu.main]]
identifier = "section.ap-home"
name = "Home"
parent = "menu.allpages"
post = 1
weight = 5
[[menu.main]]
identifier = "section.ap-about"
name = "About"
parent = "menu.allpages"
post = 1
weight = 18
[[menu.main]]
identifier = "section.ap-marketing"
name = "Marketing"
parent = "menu.allpages"
post = 1
weight = 27
[[menu.main]]
identifier = "section.ap-portfolio"
name = "Portfolio"
parent = "menu.allpages"
post = 2
weight = 4
[[menu.main]]
identifier = "section.ap-userpages"
name = "User Pages"
parent = "menu.allpages"
post = 2
weight = 17
[[menu.main]]
identifier = "section.ap-shop"
name = "Shop"
parent = "menu.allpages"
post = 3
weight = 3
[[menu.main]]
identifier = "section.ap-contact"
name = "Contact"
parent = "menu.allpages"
post = 4
weight = 2
[[menu.main]]
identifier = "section.ap-pages"
name = "Pages"
parent = "menu.allpages"
post = 4
weight = 15
[[menu.main]]
identifier = "section.ap-blog"
name = "Blog"
parent = "menu.allpages"
post = 4
url = "/blog/"
weight = 26
[[menu.main]]
name = "Blog Listing Big"
parent = "section.ap-blog"
url = "/blog/"
weight = 1
[[menu.main]]
identifier = "menu.blog"
name = "Blog"
url = "/blog/"
weight = 39
[[menu.main]]
identifier = "menu.faq"
name = "FAQ!"
url = "/faq/"
weight = 43
[[menu.main]]
identifier = "contact"
name = "Contact"
url = "/contact/"
weight = 46
[[menu.topbar]]
name = "Phone"
pre = "<i class='fas fa-2x fa-phone'></i>"
url = "tel:+62 081 826 74 43"
weight = 1
[[menu.topbar]]
name = "Facebook"
pre = "<i class='fab fa-2x fa-facebook'></i>"
url = "http://facebook.com"
weight = 2
[[menu.topbar]]
name = "Instagram"
pre = "<i class='fab fa-2x fa-instagram'></i>"
url = "http://www.instagram.com"
weight = 3
[params]
about_us = "<p>• Jam Operasional 09.00 – 22.00 WIB.<br>• Pengantaran dan pengambilan mobil/motor mulai jam 09.00-21.00 WIB. Diluar jam diatas bisa langsung datang ke garasi kami.<br>• 3 Tanda pengenal/ID (KTP,NPWP,SIM,PASPORT,ID KERJA,BPJS).<br>• No Telp HP customer yang bisa dihubungi.<br>• Tanpa uang jaminan.<br>• Overtime 10% per jam dari tarif sewa.<br>• Saat hari high season harga berbeda dengan harga hari normal</p>"
address = "<p class=\"text-uppercase\"><strong>Bening Abadi Transport</strong>\n        <br>Jl. Nusa Indah CT6 No.22B\n        <br>Samirono\n        <br>Kelurahan Caturtunggal\n        <br>Kecamatan Depok, Kabupaten Sleman, DIY\n        <br>\n        <strong>Indonesia</strong>\n      </p>\n      "
author = "Bening"
contact_form_ajax = false
contact_url = "/contact"
copyright = "Bening Abadi @2022"
date_format = "January 2, 2006"
defaultDescription = "Site Bening Abadi made by devcows using hugo"
defaultKeywords = ["sewa", "rental", "penginapan"]
default_sharing_image = "img/sharing-default.png"
disabled_logo = false
enableGoogleMaps = false
enableRecaptchaInContactForm = false
facebook_site = ""
formspree_action = "https://formspree.io/sample/of/endpoint"
googleMapsApiKey = "AIzaSyAv7Sza8NSp9_l_g8G2vlo0H4ydEPn_2jY"
googleRecaptchaKey = "site_key_for_google_recaptcha"
latitude = "-12.043333"
logo = "img/logobening2.png"
logo_small = "img/logobening2.png"
logo_text = "Bening Abadi Jogja"
longitude = "-77.028333"
mainSections = ["blog"]
style = "default"
twitter_site = "GoHugoIO"
viewMorePostLink = "/blog/"
[params.carouselCustomers]
auto_play = true
items = 6
pagination_speed = 1000
slide_speed = 500
[params.carouselHomepage]
auto_play = true
enable = true
pagination_speed = 500
slide_speed = 100
[params.carouselTestimonals]
auto_play = true
items = 4
pagination_speed = 500
slide_speed = 100
[params.clients]
enable = true
subtitle = "Mulai 250k perhari lepas kunci!"
title = "Sewa Mobil Jogja"
[params.clients2]
enable = true
subtitle = "Mulai 70k perhari!"
title = "Rental Motor Jogja"
[params.features]
cols = 3
enable = true
[params.footer.recent_posts]
enable = false
[params.recent_posts]
enable = true
hide_summary = false
subtitle = "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo."
title = "From our blog"
[params.see_more]
enable = true
icon = "far fa-file-alt"
link_text = "Check other homepages"
link_url = "#"
subtitle = "We have prepared for you more than 40 different HTML pages, including 5 variations of homepage."
title = "Do you want to see more?"
[params.testimonials]
enable = false
subtitle = "We have worked with many clients and we always like to hear they come out from the cooperation happy and satisfied. Have a look what our clients said about us."
title = "Testimonials"
[params.topbar]
enable = true
text = """"""
[params.widgets]
categories = false
search = false
tags = true
[permalinks]
blog = "/blog/:year/:month/:day/:filename/"
[taxonomies]
author = "authors"
category = "categories"
tag = "tags"
